### ISSUE TITLE
Required attribute not working on select field

### ISSUE THREAD

**Issue by otatechie** [Choices-js/Choices#1007]
**Describe the bug**
The required attribute is a boolean attribute.
When present, it specifies the user is required to select a value before submitting the form.

**Expected behavior**
If present on any of these input types and elements, the [:required](https://developer.mozilla.org/en-US/docs/Web/CSS/:required) pseudo class will match.

**Desktop (please complete the following information):**
 - Browser [e.g. Brave]
 - Version [e.g. 1.35.100]

**Additional context**
Required helps provide an indication to users informing them the form control is required. The aria-required attribute indicates that user input is required on the element before a form may be submitted improving accessibility.

**Comment by mtriff** [comment]
Please provide a simplified code example demonstrating the bug.

**Comment by atoaugustyn** [comment]
```
<select class="js-choice">
    <option value="">Please select </option>
    <option value="Red">Red </option>
    <option value="Yellow">Yellow </option>
</select>

<script>
    const choices = new Choices('.js-choice');
</script>
```

**Comment by amineo** [comment]
@thehappytechie There appears to be CSS only fix mentioned in #449.

```css
.choices[data-type*="select-one"] select.choices__input {
  display: block !important;
  opacity: 0;
  pointer-events: none;
  position: absolute;
  left: 0;
  bottom: 0;
}
```
