### ISSUE TITLE
Purpose of itemSelectText "Click to select"

### ISSUE THREAD

**Issue by thomasfrobieter** [Choices-js/Choices#1102]
This is not really a bug, I try to understand the sense of the itemSelectText "Click to select".
Imagine each single button on the web and your OS have this text inside.

For me, this is an 100% self-evident UI-action, that doesnt need any explaination.

Or is it an accessibility option? If it is, there is maybe a better way to solve this, instead wasting so much space? (aria-label, ...?)

![choices-width-bug](https://user-images.githubusercontent.com/4060313/216555044-f91ed3a2-3031-4805-9100-3c39e9f3c477.png)

**Comment by Eric-Arellano** [comment]
I agree. FYI you can disable this mechanism with the following config:

```javascript
new Choices(..., {
  itemSelectText: "",
});
```

```css
.choices__list--dropdown .choices__item--selectable,
.choices__list[aria-expanded] .choices__item--selectable {
  /* Choices.js sets this to 100px to account for itemSelectText. But we disable that,
    so we want to use the normal padding it would otherwise use of 10px. */
  padding-right: 10px;
}
```
