### ISSUE TITLE
Bootstrap 4 theming

### ISSUE THREAD

**Issue by michaelongithub** [Choices-js/Choices#828]
**Is your feature request related to a problem? Please describe.**
Have many apps that use Bootstrap 4 styling. Need to comply to that

**Describe the solution you'd like**
Bootstrap 4 styling. Css file that can be added for that.

**Describe alternatives you've considered**
not using choices
**Additional context**
Is there already one in this rep and I have not found it. Also in wiki no hints for theming.

Thanks for info, Michael

**Comment by dessalines** [comment]
A simple thing would just be a default adding of bs4 classes, I'm trying to do this now.

**Comment by dessalines** [comment]
This one is somewhat tolerable:

```
        let choices = new Choices(selectId, {
          shouldSort: false,
          classNames: {
            containerInner: 'choices__inner bg-secondary border-none',
            input: 'form-control',
            item: 'choices__item bg-secondary',
            highlightedState: 'text-info',
            selectedState: 'text-info',
          },
        });

```

**Comment by tegandbiscuits** [comment]
If your using Sass in your project, you can import the source styles and override the variables instead of including the built css.

This is what I'm setting.

```scss
// Assumes bootstrap variables are imported or overridden before here
$choices-font-size-lg: $font-size-lg;
$choices-font-size-md: $font-size-base;
$choices-font-size-sm: $font-size-sm;
$choices-guttering: $grid-gutter-width;

$choices-border-radius: 0;
$choices-border-radius-item: 0;
@if $enable-rounded {
  $choices-border-radius: $border-radius;
  $choices-border-radius-item: $rounded-pill;
}

$choices-bg-color: $input-bg;
$choices-bg-color-disabled: $input-disabled-bg;
$choices-bg-color-dropdown: $input-bg;
$choices-text-color: $input-color;
$choices-keyline-color: $input-border-color;
$choices-primary-color: $primary;
$choices-disabled-color: $input-disabled-bg;
```

Then after setting those you can import

```scss
@import '~choices.js/src/styles/choices';
```

[Here's a link to the current variables.](https://github.com/jshjohnson/Choices/blob/ebbea8c3b0f20473e05112f61bc8ce3bd6bf12da/src/styles/choices.scss#L5)

`$choices-highlight-color`, `$choices-button-dimension`, and `$choices-button-offset` are the only other ones that look worth overriding.

**Comment by ryanmortier** [comment]
@tegandbiscuits I had to tweek it a bit as it was slightly off. Here is what I used in my Sass.

```scss
$choices-font-size-lg: $input-font-size-lg;
$choices-font-size-md: $input-font-size;
$choices-font-size-sm: $input-font-size-sm;
$choices-guttering: $form-grid-gutter-width;

$choices-border-radius: 0;
$choices-border-radius-item: 0;
@if $enable-rounded {
    $choices-border-radius: $input-border-radius;
    $choices-border-radius-item: $rounded-pill;
}

$choices-bg-color: $input-bg;
$choices-bg-color-disabled: $input-disabled-bg;
$choices-bg-color-dropdown: $input-bg;
$choices-text-color: $input-color;
$choices-keyline-color: $input-border-color;
$choices-primary-color: $primary;
$choices-disabled-color: $input-disabled-bg;

@import '~choices.js/src/styles/choices';

.choices__inner {
    color: $choices-text-color; // For some reason this needs to be manually specified or it grabs the body color?
    padding-top: 6px !important;
    padding-bottom: 6px !important;
    padding-left: 8px !important;
    min-height: 38px !important;
}

.choices__list--single {
    padding-top: 0 !important;
    padding-bottom: 0 !important;
}
```

**Comment by mtriff** [comment]
It looks like the above are valid approaches. I'll happily review a PR to make an optional Bootstrap style available in the package.

**Comment by OzzyCzech** [comment]
Hi there, thanks a lot! Here is my version for [Bootstrap 5](https://getbootstrap.com/docs/5.0/getting-started/introduction/)

```
@import "../../../../../node_modules/bootstrap/scss/functions.scss";
@import "../../../../../node_modules/bootstrap/scss/variables.scss";
@import "../../../../../node_modules/bootstrap/scss/mixins.scss";

$choices-font-size-lg: $input-font-size-lg;
$choices-font-size-md: $input-font-size;
$choices-font-size-sm: $input-font-size-sm;
$choices-guttering: $spacer;

$choices-border-radius: 0;
$choices-border-radius-item: 0;
@if $enable-rounded {
	$choices-border-radius: $input-border-radius;
	$choices-border-radius-item: $border-radius-pill;
}

$choices-bg-color: $input-bg;
$choices-bg-color-disabled: $input-disabled-bg;
$choices-bg-color-dropdown: $input-bg;
$choices-text-color: $input-color;
$choices-keyline-color: $input-border-color;
$choices-primary-color: $primary;
$choices-disabled-color: $input-disabled-bg;

@import "../../../../../node_modules/choices.js/src/styles/choices.scss";

.choices__inner {
	color: $choices-text-color;
	padding: $form-select-padding-y $form-select-padding-x;
	line-height: $form-select-line-height;
	min-height: inherit;
}

.choices__list--single {
	padding-top: 0 !important;
	padding-bottom: 0 !important;
}

.choices[data-type*=select-one] .choices__inner {
	padding-bottom: 0 !important;
}

.choices[data-type*='select-one']:after {
	background-color: $form-select-bg;
	background-image: escape-svg($form-select-indicator);
	background-repeat: no-repeat;
	background-position: center center;
	background-size: contain;
	padding: 0;
	margin: 0;
	border: none;
	appearance: none;
	width: 16px;
	height: 12px;
	position: absolute;
	top: calc(50% - 5px);
	right: 10px;
}

.choices[data-type*='select-one'].is-open:after {
	transform: rotate(180deg);
	padding: 0;
	margin: 0;
}

.choices .choices__list {
	z-index: 99999;
	white-space: nowrap;
	overflow-x: hidden;
	text-overflow: ellipsis;
}
```

**Comment by daikoz** [comment]
Finally, we migrate to tomselect.
Here my version for bootstrap 5 and choices 10.1.0 (only for single select).

```scss
/* ===============================
=            Choices            =
=============================== */

@use "sass:color";

$choices-selector: "choices" !default;
$choices-font-size-lg: 1rem !default;
$choices-font-size-md: 1rem !default;
$choices-font-size-sm: 1rem !default;
$choices-guttering: 0px !default;
$choices-border-radius: .25rem !default;
$choices-border-radius-item: 20px !default;
$choices-bg-color: #f9f9f9 !default;
$choices-bg-color-disabled: #eaeaea !default;
$choices-bg-color-dropdown: #fff !default;
$choices-text-color: #333 !default;
$choices-keyline-color: #ced4da !default;
$choices-keyline-invalid-color: #dc3545 !default;
$choices-keyline-focus-color: #86b7fe !default;
$choices-primary-color: #00bcd4 !default;
$choices-disabled-color: #eaeaea !default;
$choices-highlight-color: $choices-primary-color !default;
$choices-button-dimension: 8px !default;
$choices-button-offset: 8px !default;
$choices-icon-cross: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23000'%3e%3cpath d='M.293.293a1 1 0 0 1 1.414 0L8 6.586 14.293.293a1 1 0 1 1 1.414 1.414L9.414 8l6.293 6.293a1 1 0 0 1-1.414 1.414L8 9.414l-6.293 6.293a1 1 0 0 1-1.414-1.414L6.586 8 .293 1.707a1 1 0 0 1 0-1.414z'/%3e%3c/svg%3e") !default;
$choices-icon-cross-inverse: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23000'%3e%3cpath d='M.293.293a1 1 0 0 1 1.414 0L8 6.586 14.293.293a1 1 0 1 1 1.414 1.414L9.414 8l6.293 6.293a1 1 0 0 1-1.414 1.414L8 9.414l-6.293 6.293a1 1 0 0 1-1.414-1.414L6.586 8 .293 1.707a1 1 0 0 1 0-1.414z'/%3e%3c/svg%3e") !default;
$choices-z-index: 3 !default;

.#{$choices-selector} {
    position: relative;
    overflow: hidden;
    margin-bottom: $choices-guttering;
    font-size: $choices-font-size-lg;

    &:focus {
        outline: none;
    }

    &:last-child {
        margin-bottom: 0;
    }

    &.is-open {
        overflow: visible;
    }

    &.is-disabled {

        .#{$choices-selector}__inner,
        .#{$choices-selector}__input {
            background-color: $choices-bg-color-disabled;
            cursor: not-allowed;
            user-select: none;
        }

        .#{$choices-selector}__item {
            cursor: not-allowed;
        }
    }

    [hidden] {
        display: none !important;
    }
}

.#{$choices-selector}[data-type*='select-one'] {
    cursor: pointer;

    .#{$choices-selector}__input {
        display: block;
        width: 100%;
        padding: 10px;
        border-bottom: 1px solid $choices-keyline-color;
        background-color: #fff;
        margin: 0;
    }

    .#{$choices-selector}__button {
        background-image: $choices-icon-cross-inverse;
        padding: 0;
        background-size: 11px;
        position: absolute;
        top: 50%;
        right: 0;
        margin-top: -10px;
        margin-right: 25px;
        height: 20px;
        width: 20px;
        border-radius: 10em;
        opacity: 0.5;

        &:hover,
        &:focus {
            opacity: 1;
        }

        &:focus {
            box-shadow: 0 0 0 2px $choices-highlight-color;
        }
    }

    .#{$choices-selector}__item[data-value=''] .#{$choices-selector}__button {
        display: none;
    }

    &::after {
        content: "";
        height: 0;
        width: 0;
        border-style: solid;
        border-color: $choices-text-color transparent transparent transparent;
        border-width: 5px;
        position: absolute;
        right: 11.5px;
        top: 50%;
        margin-top: -2.5px;
        pointer-events: none;
    }

    &.is-open::after {
        border-color: transparent transparent $choices-text-color transparent;
        margin-top: -7.5px;
    }

    &[dir="rtl"] {
        &::after {
            left: 11.5px;
            right: auto;
        }

        .#{$choices-selector}__button {
            right: auto;
            left: 0;
            margin-left: 25px;
            margin-right: 0;
        }
    }
}

.#{$choices-selector}[data-type*='select-multiple'],
.#{$choices-selector}[data-type*='text'] {
    .#{$choices-selector}__inner {
        cursor: text;
    }

    .#{$choices-selector}__button {
        position: relative;
        display: inline-block;
        margin-top: 0;
        margin-right: -$choices-button-offset * 0.5;
        margin-bottom: 0;
        margin-left: $choices-button-offset;
        padding-left: $choices-button-offset * 2;
        border-left: 1px solid color.adjust($choices-primary-color, $lightness: -10%);
        background-image: $choices-icon-cross;
        background-size: $choices-button-dimension;
        width: $choices-button-dimension;
        line-height: 1;
        opacity: 0.75;
        border-radius: 0;

        &:hover,
        &:focus {
            opacity: 1;
        }
    }
}

.#{$choices-selector}__inner {
    display: inline-block;
    vertical-align: top;
    width: 100%;
    padding: .375rem .8rem;
    border: 1px solid $choices-keyline-color;
    border-radius: $choices-border-radius;
    font-size: $choices-font-size-md;
    overflow: hidden;
    background-color: $choices-bg-color-dropdown;

    .is-open & {
        border-color: $choices-keyline-focus-color;
        box-shadow: 0 0 0 .25rem rgba(13,110,253,.25);
    }

    .is-invalid & {
        border-color: $choices-keyline-invalid-color;
    }

    .is-open.is-invalid & {
        box-shadow: 0 0 0 0.25rem rgb(220 53 69 / 25%);
    }
}

.#{$choices-selector}__list {
    margin: 0;
    padding-left: 0;
    list-style: none;

    &[aria-expanded] {
        @extend %choices-dropdown;
    }
}

.#{$choices-selector}__list--single {
    display: inline-block;
    width: 100%;

    [dir="rtl"] & {
        padding-right: 4px;
        padding-left: 16px;
    }

    .#{$choices-selector}__item {
        width: 100%;
    }
}

.#{$choices-selector}__list--multiple {
    display: inline;

    .#{$choices-selector}__item {
        display: inline-block;
        vertical-align: middle;
        border-radius: $choices-border-radius-item;
        padding: 4px 10px;
        font-size: $choices-font-size-sm;
        font-weight: 500;
        margin-right: 3.75px;
        margin-bottom: 3.75px;
        background-color: $choices-primary-color;
        border: 1px solid color.adjust($choices-primary-color, $lightness: -5%);
        color: #fff;
        word-break: break-all;
        box-sizing: border-box;

        &[data-deletable] {
            padding-right: 5px;
        }

        [dir="rtl"] & {
            margin-right: 0;
            margin-left: 3.75px;
        }

        &.is-highlighted {
            background-color: color.adjust($choices-primary-color, $lightness: -5%);
            border: 1px solid color.adjust($choices-primary-color, $lightness: -10%);
        }

        .is-disabled & {
            background-color: color.adjust($choices-disabled-color, $lightness: -25%);
            border: 1px solid color.adjust($choices-disabled-color, $lightness: -35%);
        }
    }
}

%choices-dropdown {
    visibility: hidden;
    z-index: $choices-z-index;
    position: absolute;
    width: 100%;
    background-color: $choices-bg-color-dropdown;
    border: 1px solid $choices-keyline-color;
    top: 100%;
    margin-top: -1px;
    border-radius: $choices-border-radius;
    overflow: hidden;
    word-break: break-all;
    will-change: visibility;

    &.is-active {
        visibility: visible;
    }

    .is-open & {
        border-left-color: $choices-keyline-focus-color;
        border-bottom-color: $choices-keyline-focus-color;
        border-right-color: $choices-keyline-focus-color;
        box-shadow: 0 1px 4px 1px rgba(13,110,253,.25);
    }

    .is-open.is-flipped & {
        border-left-color: $choices-keyline-focus-color;
        border-bottom-color: $choices-keyline-color;
        border-top-color: $choices-keyline-focus-color;
        border-right-color: $choices-keyline-focus-color;
        box-shadow: 0 -1px 4px 1px rgba(13,110,253,.25);
    }

    .is-open.is-invalid & {
        border-left-color: $choices-keyline-invalid-color;
        border-bottom-color: $choices-keyline-invalid-color;
        border-right-color: $choices-keyline-invalid-color;
        box-shadow: 0 1px 4px 1px rgb(220 53 69 / 25%);
    }

    .is-open.is-flipped.is-invalid & {
        border-left-color: $choices-keyline-invalid-color;
        border-top-color: $choices-keyline-invalid-color;
        border-bottom-color: $choices-keyline-color;
        border-right-color: $choices-keyline-invalid-color;
        box-shadow: 0 -1px 4px 1px rgb(220 53 69 / 25%);
    }

    .is-flipped & {
        top: auto;
        bottom: 100%;
        margin-top: 0;
        margin-bottom: -1px;
    }

    .#{$choices-selector}__list {
        position: relative;
        max-height: 300px;
        overflow: auto;
        -webkit-overflow-scrolling: touch;
        will-change: scroll-position;
    }

    .#{$choices-selector}__item {
        position: relative;
        padding: 10px;
        font-size: $choices-font-size-md;

        [dir="rtl"] & {
            text-align: right;
        }
    }

    .#{$choices-selector}__item--selectable {
        @media (min-width: 640px) {

            &::after {
                content: attr(data-select-text);
                font-size: $choices-font-size-sm;
                opacity: 0;
                position: absolute;
                right: 10px;
                top: 50%;
                transform: translateY(-50%);
            }

            [dir="rtl"] & {
                text-align: right;
                padding-left: 100px;
                padding-right: 10px;

                &::after {
                    right: auto;
                    left: 10px;
                }
            }
        }

        &.is-highlighted {
            background-color: color.mix(#000, #fff, 5%);

            &::after {
                opacity: 0.5;
            }
        }
    }
}

.#{$choices-selector}__list--dropdown {
    @extend %choices-dropdown;
}

.#{$choices-selector}__item {
    cursor: default;
}

.#{$choices-selector}__item--selectable {
    cursor: pointer;
}

.#{$choices-selector}__item--disabled {
    cursor: not-allowed;
    user-select: none;
    opacity: 0.5;
}

.#{$choices-selector}__heading {
    font-weight: 600;
    font-size: $choices-font-size-sm;
    padding: 10px;
    border-bottom: 1px solid color.adjust($choices-keyline-color, $lightness: 10%);
    color: color.adjust(#333, $lightness: 30%);
}

.#{$choices-selector}__button {
    text-indent: -9999px;
    appearance: none;
    border: 0;
    background-color: transparent;
    background-repeat: no-repeat;
    background-position: center;
    cursor: pointer;

    &:focus {
        outline: none;
    }
}

.#{$choices-selector}__input {
    display: inline-block;
    vertical-align: baseline;
    background-color: $choices-bg-color;
    font-size: $choices-font-size-md;
    margin-bottom: 5px;
    border: 0;
    border-radius: 0;
    max-width: 100%;
    padding: 4px 0 4px 2px;

    &:focus {
        outline: 0;
    }

    &::-webkit-search-decoration,
    &::-webkit-search-cancel-button,
    &::-webkit-search-results-button,
    &::-webkit-search-results-decoration {
        display: none;
    }

    &::-ms-clear,
    &::-ms-reveal {
        display: none;
        width: 0;
        height: 0;
    }

    [dir="rtl"] & {
        padding-right: 2px;
        padding-left: 0;
    }
}

.#{$choices-selector}__placeholder {
    color: #6c757d;
}


.#{$choices-selector}__list--dropdown > .#{$choices-selector}__list > .#{$choices-selector}__placeholder {
    display: none;
}

.#{$choices-selector}__item--selectable + .#{$choices-selector}__placeholder {
    display: none;
}


/* =====  End of Choices  ====== */
```
